name: Update packages.json from CRAN Task View

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3 * * 3'

jobs:
  update-packages-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tibble
            dplyr
            glue
            jsonlite

      - run: Rscript create_universe.R

      - name: Save data/source_repositories.csv
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add packages.json
          git diff-index --quiet HEAD || git commit -m 'Add new pkgs from the CRAN Task View'
          git pull --rebase origin main
          git push
          echo "pushed to github"
