name: Update packages.json from CRAN Task View

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tibble
            dplyr
            glue
            jsonlite

      - run: Rscript create_universe.R
